### ISSUE TITLE
terminate called after throwing an instance of 'msgpack::v1::insufficient_bytes'

### ISSUE THREAD

**Issue by IndianBoy42** [rohit-px2/nvui#23]
Hi I am suddenly having a strange issue whenever I try open `nvui`

```
terminate called after throwing an instance of 'msgpack::v1::insufficient_bytes'
  what():  insufficient bytes
fish: Job 2, 'nvui' terminated by signal SIGABRT (Abort)
```

The strange thing is, this only happens if I dont load a session on startup (actually the loading is done by a plugin). So in a new directory, nvui can't launch, but if I launch `nvim` and then save a session, then I can open by `nvui`

**Comment by IndianBoy42** [comment]
Actually It might not be the session but it might be the lack of any buffers open? because `nvui somefile` works. Although I should have a dashboard open so I don't know

**Comment by rohit-px2** [comment]
#42 should fix this.

**Comment by IndianBoy42** [comment]
```
terminate called after throwing an instance of 'msgpack::v1::type_error'
  what():  std::bad_cast
```

I still get this error on the latest release, in a very similar situation

**Comment by IndianBoy42** [comment]
Actually know that basically always happens, whether I open a file/have a session etc

**Comment by rohit-px2** [comment]
Could you try running nvui with `--ext_hlstate=false` and see if that works?

**Comment by rohit-px2** [comment]
@IndianBoy42 release v0.1.3 should fix this issue, let me know if you are still having issues
